log:
  level: debug
  disable_sentry: true

db:
  url: postgres://core:core@localhost:5432/core?sslmode=disable

listener:
  addr: :8010

registration_api:
  addr: :8011

cop:
  disabled: true
  endpoint: "http://localhost:90"
  upstream: "http://localhost:88"
  service_name: blob-svc
  service_port: 88
